### ISSUE TITLE
Support for changing ctime for directories

### ISSUE THREAD

**Issue by RomulBY** [Delgan/win32-setctime#3]
Add support for changing ctime for directories, please.

**Comment by Delgan** [comment]
This seems to be a welcome improvement. I updated the `set_ctime()` function so that it supports directories too, you can update to `v1.0.3` and it should work.

This was pretty easy, according to [the documentation](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew#directories), it only requires to specify the `FILE_FLAG_BACKUP_SEMANTICS` flag... Except this is wrong.
While doing some research, I came across this very interesting message which explains the problems related to this flag (basically, it's about user privileges): https://github.com/ocaml/ocaml/pull/8797
Considering how complicated it would be for me to implement an alternative solution, I accept the trade-off of using an imperfect function.

**Comment by RomulBY** [comment]
Thank you very much! You made my day :)
